import { Transaction } from "./model";

export const sampleTransactions: Transaction[] = [
  {
    id: "txn_001",
    amount: 87.43,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-28",
    merchantName: "Whole Foods Market",
    categoryId: "grocery",
    mcc: "5411",
    accountId: "acc_001",
    description: "Weekly groceries",
  },
  {
    id: "txn_002",
    amount: 45.0,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-27",
    merchantName: "Shell Gas Station",
    categoryId: "gas",
    mcc: "5541",
    accountId: "acc_001",
  },
  {
    id: "txn_003",
    amount: 3200.0,
    currency: "USD",
    type: "credit",
    status: "posted",
    date: "2024-08-26",
    merchantName: "ACME Corporation",
    categoryId: "salary",
    mcc: "0000",
    accountId: "acc_001",
    description: "Bi-weekly salary",
  },
  {
    id: "txn_004",
    amount: 12.99,
    currency: "USD",
    type: "debit",
    status: "pending",
    date: "2024-08-28",
    merchantName: "Netflix",
    categoryId: "streaming",
    mcc: "7841",
    accountId: "acc_001",
    description: "Monthly subscription",
  },
  {
    id: "txn_005",
    amount: 2.5,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-25",
    merchantName: "Chase ATM",
    categoryId: "fees",
    mcc: "6011",
    accountId: "acc_001",
    description: "ATM withdrawal fee",
  },
  {
    id: "txn_006",
    amount: 156.78,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-24",
    merchantName: "Home Depot",
    categoryId: "home_improvement",
    mcc: "5211",
    accountId: "acc_001",
    description: "Bathroom renovation supplies",
  },
  {
    id: "txn_007",
    amount: 23.45,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-23",
    merchantName: "Starbucks",
    categoryId: "coffee",
    mcc: "5814",
    accountId: "acc_001",
  },
  {
    id: "txn_008",
    amount: 892.33,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-22",
    merchantName: "Apple Store",
    categoryId: "electronics",
    mcc: "5732",
    accountId: "acc_002",
    description: "iPhone 15 Pro",
  },
  {
    id: "txn_009",
    amount: 67.89,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-21",
    merchantName: "Target",
    categoryId: "shopping",
    mcc: "5310",
    accountId: "acc_001",
  },
  {
    id: "txn_010",
    amount: 1250.0,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-20",
    merchantName: "Delta Airlines",
    categoryId: "travel",
    mcc: "4511",
    accountId: "acc_002",
    description: "Flight to NYC",
  },
  {
    id: "txn_011",
    amount: 15.99,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-19",
    merchantName: "Spotify",
    categoryId: "streaming",
    mcc: "7372",
    accountId: "acc_001",
    description: "Premium subscription",
  },
  {
    id: "txn_012",
    amount: 78.5,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-18",
    merchantName: "CVS Pharmacy",
    categoryId: "pharmacy",
    mcc: "5912",
    accountId: "acc_001",
    description: "Prescription medication",
  },
  {
    id: "txn_013",
    amount: 234.67,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-17",
    merchantName: "Nordstrom",
    categoryId: "clothing",
    mcc: "5651",
    accountId: "acc_002",
  },
  {
    id: "txn_014",
    amount: 42.88,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-16",
    merchantName: "Uber",
    categoryId: "transportation",
    mcc: "4121",
    accountId: "acc_001",
    description: "Ride to airport",
  },
  {
    id: "txn_015",
    amount: 450.0,
    currency: "USD",
    type: "credit",
    status: "posted",
    date: "2024-08-15",
    merchantName: "Freelance Client",
    categoryId: "freelance",
    mcc: "0000",
    accountId: "acc_001",
    description: "Website design project",
  },
  {
    id: "txn_016",
    amount: 89.99,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-14",
    merchantName: "Amazon",
    categoryId: "shopping",
    mcc: "5969",
    accountId: "acc_001",
    description: "Prime membership renewal",
  },
  {
    id: "txn_017",
    amount: 125.0,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-13",
    merchantName: "LA Fitness",
    categoryId: "fitness",
    mcc: "7997",
    accountId: "acc_001",
    description: "Monthly gym membership",
  },
  {
    id: "txn_018",
    amount: 34.56,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-12",
    merchantName: "Chipotle",
    categoryId: "restaurants",
    mcc: "5814",
    accountId: "acc_001",
    description: "Lunch",
  },
  {
    id: "txn_019",
    amount: 189.0,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-11",
    merchantName: "Verizon",
    categoryId: "phone",
    mcc: "4814",
    accountId: "acc_001",
    description: "Monthly cell phone bill",
  },
  {
    id: "txn_020",
    amount: 8.75,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-10",
    merchantName: "Dunkin Donuts",
    categoryId: "coffee",
    mcc: "5814",
    accountId: "acc_001",
  },
  {
    id: "txn_021",
    amount: 1450.0,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-09",
    merchantName: "ABC Property Management",
    categoryId: "rent",
    mcc: "6513",
    accountId: "acc_001",
    description: "Monthly rent",
  },
  {
    id: "txn_022",
    amount: 52.34,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-08",
    merchantName: "Costco",
    categoryId: "grocery",
    mcc: "5411",
    accountId: "acc_001",
  },
  {
    id: "txn_023",
    amount: 225.0,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-07",
    merchantName: "Dr. Smith Dentist",
    categoryId: "medical",
    mcc: "8021",
    accountId: "acc_002",
    description: "Routine cleaning",
  },
  {
    id: "txn_024",
    amount: 35.0,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-06",
    merchantName: "Shell Gas Station",
    categoryId: "gas",
    mcc: "5541",
    accountId: "acc_001",
  },
  {
    id: "txn_025",
    amount: 16.49,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-05",
    merchantName: "McDonalds",
    categoryId: "fast_food",
    mcc: "5814",
    accountId: "acc_001",
    description: "Drive-thru dinner",
  },
  {
    id: "txn_026",
    amount: 150.0,
    currency: "USD",
    type: "credit",
    status: "posted",
    date: "2024-08-04",
    merchantName: "IRS",
    categoryId: "refund",
    mcc: "9311",
    accountId: "acc_001",
    description: "Tax refund",
  },
  {
    id: "txn_027",
    amount: 89.45,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-03",
    merchantName: "Barnes & Noble",
    categoryId: "books",
    mcc: "5942",
    accountId: "acc_001",
  },
  {
    id: "txn_028",
    amount: 25.99,
    currency: "USD",
    type: "debit",
    status: "pending",
    date: "2024-08-28",
    merchantName: "Adobe",
    categoryId: "software",
    mcc: "5734",
    accountId: "acc_001",
    description: "Creative Cloud subscription",
  },
  {
    id: "txn_029",
    amount: 340.78,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-02",
    merchantName: "Best Buy",
    categoryId: "electronics",
    mcc: "5732",
    accountId: "acc_001",
    description: "Gaming headset",
  },
  {
    id: "txn_030",
    amount: 65.0,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-08-01",
    merchantName: "Olive Garden",
    categoryId: "restaurants",
    mcc: "5812",
    accountId: "acc_002",
    description: "Date night dinner",
  },
  {
    id: "txn_031",
    amount: 125.5,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-07-31",
    merchantName: "ComEd",
    categoryId: "utilities",
    mcc: "4900",
    accountId: "acc_001",
    description: "Electric bill",
  },
  {
    id: "txn_032",
    amount: 19.99,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-07-30",
    merchantName: "Disney Plus",
    categoryId: "streaming",
    mcc: "7841",
    accountId: "acc_001",
    description: "Monthly subscription",
  },
  {
    id: "txn_033",
    amount: 200.0,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-07-29",
    merchantName: "Cash Withdrawal",
    categoryId: "cash",
    mcc: "6011",
    accountId: "acc_001",
    description: "ATM withdrawal",
  },
  {
    id: "txn_034",
    amount: 78.99,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-07-28",
    merchantName: "TJ Maxx",
    categoryId: "clothing",
    mcc: "5651",
    accountId: "acc_001",
  },
  {
    id: "txn_035",
    amount: 1250.0,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-07-27",
    merchantName: "Toyota Service Center",
    categoryId: "auto_repair",
    mcc: "7538",
    accountId: "acc_002",
    description: "Oil change and brake service",
  },
  {
    id: "txn_036",
    amount: 9.99,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-07-26",
    merchantName: "The New York Times",
    categoryId: "news",
    mcc: "5994",
    accountId: "acc_001",
    description: "Digital subscription",
  },
  {
    id: "txn_037",
    amount: 145.0,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-07-25",
    merchantName: "Progressive Insurance",
    categoryId: "insurance",
    mcc: "6300",
    accountId: "acc_001",
    description: "Auto insurance premium",
  },
  {
    id: "txn_038",
    amount: 42.5,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-07-24",
    merchantName: "Trader Joes",
    categoryId: "grocery",
    mcc: "5411",
    accountId: "acc_001",
  },
  {
    id: "txn_039",
    amount: 2850.0,
    currency: "USD",
    type: "credit",
    status: "posted",
    date: "2024-07-23",
    merchantName: "Tech Corp",
    categoryId: "salary",
    mcc: "0000",
    accountId: "acc_001",
    description: "Bi-weekly paycheck",
  },
  {
    id: "txn_040",
    amount: 28.75,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-07-22",
    merchantName: "Panera Bread",
    categoryId: "restaurants",
    mcc: "5814",
    accountId: "acc_001",
    description: "Business lunch",
  },
  {
    id: "txn_041",
    amount: 95.0,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-07-21",
    merchantName: "AMC Theaters",
    categoryId: "entertainment",
    mcc: "7832",
    accountId: "acc_001",
    description: "Movie tickets and snacks",
  },
  {
    id: "txn_042",
    amount: 178.45,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-07-20",
    merchantName: "Petsmart",
    categoryId: "pets",
    mcc: "5995",
    accountId: "acc_001",
    description: "Dog food and toys",
  },
  {
    id: "txn_043",
    amount: 5.25,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-07-19",
    merchantName: "Parking Meter",
    categoryId: "parking",
    mcc: "7523",
    accountId: "acc_001",
  },
  {
    id: "txn_044",
    amount: 325.0,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-07-18",
    merchantName: "Marriott Hotel",
    categoryId: "hotels",
    mcc: "7011",
    accountId: "acc_002",
    description: "Business trip accommodation",
  },
  {
    id: "txn_045",
    amount: 67.89,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-07-17",
    merchantName: "Sephora",
    categoryId: "beauty",
    mcc: "5977",
    accountId: "acc_001",
  },
  {
    id: "txn_046",
    amount: 15.0,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-07-16",
    merchantName: "Lyft",
    categoryId: "transportation",
    mcc: "4121",
    accountId: "acc_001",
    description: "Ride home",
  },
  {
    id: "txn_047",
    amount: 450.75,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-07-15",
    merchantName: "Ikea",
    categoryId: "furniture",
    mcc: "5712",
    accountId: "acc_002",
    description: "Office desk and chair",
  },
  {
    id: "txn_048",
    amount: 12.5,
    currency: "USD",
    type: "debit",
    status: "pending",
    date: "2024-08-28",
    merchantName: "YouTube Premium",
    categoryId: "streaming",
    mcc: "7372",
    accountId: "acc_001",
    description: "Monthly subscription",
  },
  {
    id: "txn_049",
    amount: 85.99,
    currency: "USD",
    type: "debit",
    status: "posted",
    date: "2024-07-14",
    merchantName: "REI",
    categoryId: "outdoor",
    mcc: "5941",
    accountId: "acc_001",
    description: "Hiking boots",
  },
  {
    id: "txn_050",
    amount: 750.0,
    currency: "USD",
    type: "credit",
    status: "posted",
    date: "2024-07-13",
    merchantName: "Consulting Client XYZ",
    categoryId: "freelance",
    mcc: "0000",
    accountId: "acc_001",
    description: "Project completion bonus",
  },
];
